USE_FATFS=1
# Project Name

TARGET = sdcard

# Sources
CPP_SOURCES = sdcard.cpp ../../../src/tusenskona.cpp

# Library Locations
LIBDAISY_DIR = ../../../libDaisy/
DAISYSP_DIR = ../../../DaisySP/

# Core location, and generic Makefile.
SYSTEM_FILES_DIR = $(LIBDAISY_DIR)/core
include $(SYSTEM_FILES_DIR)/Makefile
