# Project Name
TARGET = trill

ROOT_DIR = ../../..
VIKTOR_DIR = /Users/viktorsandstrom/Documents/CPP/dsp/dsp

# Sources
CPP_SOURCES = trill.cpp $(ROOT_DIR)/src/tusenskona.cpp $(VIKTOR_DIR)/wavetable.cpp $(VIKTOR_DIR)/interpolation.cpp

# Library Locations
LIBDAISY_DIR = $(ROOT_DIR)/libDaisy
DAISYSP_DIR = $(ROOT_DIR)/DaisySP

# Core location, and generic Makefile.
SYSTEM_FILES_DIR = $(LIBDAISY_DIR)/core
include $(SYSTEM_FILES_DIR)/Makefile
